// ============================================================================
// Mots clés suivis par client (suivi mensuel de positions)
// ============================================================================
//
// Clé = domain du client (doit matcher CLIENTS dans clients.js).
// Valeur = liste de mots clés EXACTEMENT comme ils apparaissent dans GSC
// (toujours en minuscules, GSC normalise les requêtes).
//
// Pour ajuster la liste d'un client : éditer ce fichier, commit, push.
// Le dashboard se met à jour au prochain build (quotidien, ou push immédiat).
//
// Une liste vide [] = pas encore de seed. Le workflow "Seed keywords"
// (Actions > Seed keywords > Run workflow) remplit automatiquement les listes
// vides avec les top requêtes hors marque des 90 derniers jours, sans toucher
// aux listes déjà remplies.

export const KEYWORDS = {
  'thelaststep.fr': [
    "asics gel-kayano 14",
    "nike p-6000",
    "air jordan 4",
    "new balance 740",
    "nike air max 1",
    "new balance 2002r",
    "air jordan 1",
    "jordan 1",
    "jordan 1 low travis scott",
    "adidas spezial",
    "fear of god essentials",
    "p6000 noir",
    "p6000 blanche",
    "p6000 rose",
    "p6000 bleu",
    "p6000 beige",
    "p6000 argenté",
    "p6000 grise",
    "p6000 marron",
    "p6000 rouge",
    "p6000 noir et blanc",
    "p6000 doré",
    "p6000 violet",
    "p6000 noir et rose",
    "p6000 noir et gris",
    "p6000 bordeaux",
    "new balance 740 bleu",
    "new balance 740 rose",
    "new balance 740 noir",
    "new balance 740 blanche",
    "new balance 740 violet",
    "new balance 740 grise",
    "new balance 740 verte",
    "new balance 740 beige",
    "new balance 740 marron",
    "new balance 740 orange",
    "new balance 740 argentée",
  ],
  'celio.com': [
    "costume homme",
    "pantalon lin homme",
    "pantalon cargo homme",
    "pantalon en lin homme",
    "chemise homme",
    "taille pantalon homme",
    "pyjama homme",
    "short homme",
    "pantalon en lin",
    "pantalon homme",
    "pantalon chino homme",
    "polo homme",
    "bermuda homme",
    "chemise en lin homme",
    "chemise lin homme",
  ],
  'techniques-ingenieur.fr': [
    "goutte de poix live",
    "monoxyde de dihydrogène",
    "comment pirater un wifi",
    "ami labs",
    "technique d'ingénieur",
    "la goutte de poix webcam",
    "pprn",
    "semelle filante",
    "masse volumique acier",
    "vdi 2230",
    "analyse atj",
    "platine",
    "fermentation lactique",
    "spectrophotométrie",
    "bronze",
  ],
  'strap-on-me.com': [
    "strap on",
    "pegging",
    "sesso anale",
    "dildo",
    "dominatrice",
    "bdsm",
    "strapon",
    "nuru massage",
    "femme dominatrice",
    "bdsm soft",
    "soft bdsm",
    "godemichet",
    "ejaculating strap",
    "strap on harness",
    "massage erotique",
  ],
  '1969store.com': [
    "bijoux bdsm",
    "harnais pegging",
    "69 site",
    "harnais bdsm",
    "69 toys",
    "bdsm toys",
    "nalone",
    "sextoys bdsm",
    "sextoy bdsm",
    "strap on me",
    "harnais strap on me",
    "bijou bdsm",
    "dildo panty",
    "sex toys 69",
    "bondage",
  ],
  'faguo-store.com': [
    "basket femme",
    "casquette homme",
    "basket homme",
    "surchemise homme",
    "sac a dos",
    "veste homme",
    "baskets femme",
    "sac a dos homme",
    "tee shirt homme",
    "chemise homme",
    "basket blanche homme",
    "t shirt homme",
    "tshirt homme",
    "polo homme",
    "sweat homme",
  ],
  'amv.fr': [
    "assurance moto",
    "devis assurance moto",
    "assurance moto pas cher",
    "assurance scooter",
    "assurance camping car",
    "comparateur assurance moto",
    "simulation assurance moto",
    "assurance scooter 50cc",
    "assurance quad",
    "assurance en ligne",
    "assurance jet ski",
    "assurance 2 roues",
    "assurance moto cross",
    "vente moto controle technique",
    "assurance scooter 125",
  ],
  'coeo-design.com': [
    "magret de canard au kamado",
    "charbon fogon",
    "kamado francais",
    "magret au kamado",
    "poulet kamado",
    "ribs kamado",
    "brasero 974",
    "poulet au kamado",
    "kamado made in france",
    "magret kamado",
    "brasero reunion",
    "charbon argentin fogon",
    "ribs au kamado",
    "accessoires brasero",
    "brasero montpellier",
  ],
  'quitoque.fr': [
    "cuisson lentilles corail",
    "cuisson artichaut",
    "cuisson boulgour",
    "menu de la semaine",
    "asperge",
    "clou de girofle bienfaits",
    "lentilles corail cuisson",
    "panure",
    "boulgour cuisson",
    "quantité de riz par personne",
    "cuisson lentille corail",
    "menu semaine",
    "cuisson artichaut vapeur",
    "gateau sans oeuf",
    "ananas bienfaits",
  ],
};
