// ============================================================================
// Mots clés suivis par client (suivi mensuel de positions)
// ============================================================================
//
// Clé = domain du client (doit matcher CLIENTS dans clients.js).
// Valeur = liste de mots clés EXACTEMENT comme ils apparaissent dans GSC
// (toujours en minuscules, GSC normalise les requêtes).
//
// Pour ajuster la liste d'un client : éditer ce fichier, commit, push.
// Le dashboard se met à jour au prochain build (quotidien, ou push immédiat).
//
// Une liste vide [] = pas encore de seed. Le workflow "Seed keywords"
// (Actions > Seed keywords > Run workflow) remplit automatiquement les listes
// vides avec les top requêtes hors marque des 90 derniers jours, sans toucher
// aux listes déjà remplies.

export const KEYWORDS = {
  'thelaststep.fr': [
    "air max 1",
    "adidas bad bunny",
    "adidas bw army",
    "kayano 14",
    "supreme",
    "samba",
    "air max 95",
    "dunk sb",
    "nike mind 001",
    "essentials",
    "nike air max 1",
    "saucony rose",
    "air max one",
    "bw army",
    "yeezy slide",
  ],
  'celio.com': [
    "celii",
    "camaïeu",
    "camaieu",
    "celuo",
    "costume homme",
    "célio",
    "pantalon lin homme",
    "pantalon cargo homme",
    "pantalon en lin homme",
    "chemise homme",
    "taille pantalon homme",
    "pyjama homme",
    "short homme",
    "be camaieu",
    "pantalon en lin",
  ],
  'techniques-ingenieur.fr': [
    "goutte de poix live",
    "monoxyde de dihydrogène",
    "comment pirater un wifi",
    "ami labs",
    "technique d'ingénieur",
    "la goutte de poix webcam",
    "pprn",
    "semelle filante",
    "masse volumique acier",
    "vdi 2230",
    "analyse atj",
    "platine",
    "fermentation lactique",
    "spectrophotométrie",
    "bronze",
  ],
  'strap-on-me.com': [
    "strap on",
    "pegging",
    "sesso anale",
    "dildo",
    "dominatrice",
    "bdsm",
    "strapon",
    "nuru massage",
    "femme dominatrice",
    "bdsm soft",
    "soft bdsm",
    "godemichet",
    "strap me on",
    "ejaculating strap",
    "strap on harness",
  ],
  '1969store.com': [
    "bijoux bdsm",
    "harnais pegging",
    "69 site",
    "harnais bdsm",
    "69 toys",
    "bdsm toys",
    "nalone",
    "sextoys bdsm",
    "sextoy bdsm",
    "strap on me",
    "harnais strap on me",
    "bijou bdsm",
    "dildo panty",
    "sex toys 69",
    "bondage",
  ],
  'faguo-store.com': [
    "fago",
    "basket femme",
    "casquette homme",
    "basket homme",
    "surchemise homme",
    "sac a dos",
    "fuago",
    "veste homme",
    "baskets femme",
    "sac a dos homme",
    "tee shirt homme",
    "fagou",
    "chemise homme",
    "basket blanche homme",
    "t shirt homme",
  ],
  'amv.fr': [
    "assurance moto",
    "moto verte assurance",
    "devis assurance moto",
    "assurance moto pas cher",
    "assurance scooter",
    "amw",
    "assurance camping car",
    "comparateur assurance moto",
    "simulation assurance moto",
    "assurance scooter 50cc",
    "assurance quad",
    "moto verte",
    "assurance en ligne",
    "assurance jet ski",
    "assurance 2 roues",
  ],
  'coeo-design.com': [
    "magret de canard au kamado",
    "charbon fogon",
    "kamado francais",
    "magret au kamado",
    "poulet kamado",
    "ribs kamado",
    "brasero 974",
    "poulet au kamado",
    "kamado made in france",
    "magret kamado",
    "brasero reunion",
    "charbon argentin fogon",
    "ribs au kamado",
    "accessoires brasero",
    "brasero montpellier",
  ],
  'quitoque.fr': [
    "cuisson lentilles corail",
    "cuisson artichaut",
    "cuisson boulgour",
    "menu de la semaine",
    "asperge",
    "clou de girofle bienfaits",
    "lentilles corail cuisson",
    "panure",
    "boulgour cuisson",
    "quantité de riz par personne",
    "cuisson lentille corail",
    "menu semaine",
    "qui toque",
    "cuisson artichaut vapeur",
    "gateau sans oeuf",
  ],
};
